name: CatDogDenseNet
n_gpu: 0

arch: 
    type: DenseNet
    args: 
        in_channels: 3
        k: 12
        num_classes: 2
    
data_loader: 
    type: CatDogDataLoader
    args:
        data_dir: data/catdog/train/
        batch_size: 128
        shuffle: true
        validation_split: 0.1
        num_workers: 0
        resize: [224,224]
    
optimizer:
    type: Adam
    args:
        lr: 1.0e-3
        weight_decay: 0
        amsgrad: true
    
loss: nll_loss
metrics: 
    - accuracy
    - top_k_acc

lr_scheduler: 
    type: StepLR
    args: 
        step_size: 50
        gamma: 0.1
    

trainer: 
    epochs: 100
    save_dir: saved/
    save_period: 1
    verbosity: 2
    monitor: min val_loss
    early_stop: 10
    tensorboard: true
